on:
  push:
    branches:
      - main

name: ğŸš€ Deploy website on push

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ›  Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: ğŸš€ Install dependencies
        run: npm install

      - name: ğŸ— Build project
        run: npm run build

      - name: ğŸ“‚ Sync files
        id: sync-files
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: 149.202.43.245
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /var/www/blacksheepclothing.es/

      - name: Check if Sync files step was successful
        if: steps.sync-files.outcome == 'failure'
        run: exit 1 # This will stop the workflow if the Sync files step fails